### ISSUE TITLE
when i use CIKM_predrnn.py ,it run wrong

### ISSUE THREAD

**Issue by ToscanaGoGithub** [thuml/predrnn-pytorch#33]
: python experiment/CIKM_predrnn.py 

Traceback (most recent call last):
  File "experiment/CIKM_predrnn.py", line 294, in <module>
    wrapper_train(model)
  File "experiment/CIKM_predrnn.py", line 248, in wrapper_train
    cost = trainer.train(model, ims, real_input_flag, args, itr)
  File "/home/t42/zhangwei/w外推预测/RAP-Net/core/trainer.py", line 4, in train
    cost = model.train(ims, real_input_flag)
  File "/home/t42/zhangwei/w外推预测/RAP-Net/core/models/model_factory.py", line 57, in train
    next_frames = self.network(frames_tensor, mask_tensor)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/t42/zhangwei/w外推预测/RAP-Net/core/models/predict.py", line 56, in forward
    h_t[0], c_t[0], memory = self.cell_list[0](net, h_t[0], c_t[0], memory)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/t42/zhangwei/w外推预测/RAP-Net/core/layers/STLSTMCell.py", line 35, in forward
    x_concat = self.conv_x(x_t)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/t42/anaconda3/envs/predrnn/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 440, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Given groups=1, weight of size [448, 16, 5, 5], expected input[4, 32, 32, 16] to have 16 channels, but got 32 channels instead

**Comment by lsteffenel** [comment]
Have you found a solution for this problem? I got the same error when using larger images (256x256).
